# Bandit Security Linter Configuration
# Run: bandit -r backend/ -f json -o bandit-report.json

exclude_dirs:
  - '/backend/tests/'
  - '/backend/.venv/'
  - '/backend/venv/'
  - '/backend/build/'
  - '/backend/dist/'
  - '/backend/.eggs/'

tests:
  # Skip certain tests if they cause false positives
  - B201  # flask_debug_true (we use FastAPI, not Flask)
  - B301  # pickle (sometimes needed for serialization)
  - B303  # md5 (used in non-security contexts)
  - B304  # ciphers (needed for encryption)
  - B305  # cipher_modes (needed for encryption)
  - B306  # mktemp_q (rarely used)
  - B307  # eval (used in template rendering)
  - B308  # mark_safe (Django, not used here)
  - B309  # httpsconnection (false positives)
  - B310  # urllib_urlopen (false positives)
  - B311  # random (not for crypto)
  - B312  # telnetlib (rarely used)
  - B313  # xml_bad_cElementTree (false positives)
  - B314  # xml_bad_ElementTree (false positives)
  - B315  # xml_bad_expatreader (false positives)
  - B316  # xml_bad_expatbuilder (false positives)
  - B317  # xml_bad_sax (false positives)
  - B318  # xml_bad_minidom (false positives)
  - B319  # xml_bad_pulldom (false positives)
  - B320  # xml_bad_etree (false positives)
  - B321  # ftplib (false positives)
  - B322  # input (false positives)
  - B323  # unverified_context (false positives)
  - B324  # hashlib_new_insecure_functions (false positives)
  - B325  # tempnam (rarely used)
  - B401  # import_telnetlib (rarely used)
  - B402  # import_ftplib (false positives)
  - B403  # import_pickle (needed for serialization)
  - B404  # import_subprocess (needed for command execution)
  - B405  # import_xml_etree (false positives)
  - B406  # import_xml_sax (false positives)
  - B407  # import_xml_expat (false positives)
  - B408  # import_xml_minidom (false positives)
  - B409  # import_xml_pulldom (false positives)
  - B410  # import_lxml (false positives)
  - B411  # import_xmlrpclib (false positives)
  - B412  # import_httpoxy (false positives)
  - B413  # import_pycrypto (deprecated, not used)
  - B501  # request_with_no_cert_validation (needs context)
  - B502  # ssl_with_bad_version (deprecated protocol)
  - B503  # ssl_with_bad_defaults (false positives)
  - B504  # ssl_with_no_version (needs context)
  - B505  # weak_cryptographic_key (needs context)
  - B506  # yaml_load (false positives)
  - B507  # ssh_no_host_key_verification (needs context)
  - B601  # paramiko_calls (false positives)
  - B602  # subprocess_popen_with_shell_equals_true (needs context)
  - B603  # subprocess_without_shell_equals_true (needed)
  - B604  # any_other_function_with_shell_equals_true (needs context)
  - B605  # start_process_with_a_shell (needed)
  - B606  # start_process_with_no_shell (needed)
  - B607  # start_process_with_partial_path (false positives)
  - B608  # hardcoded_sql_expressions (false positives)
  - B609  # linux_commands_wildcard_injection (false positives)
  - B610  # django_extra_used (Django, not used)
  - B611  # django_rawsql_used (Django, not used)
  - B701  # jinja2_autoescape_false (needs context)
  - B702  # use_of_mako_templates (not used)
  - B703  # django_mark_safe (Django, not used)

# Security checks
assert_used:
  skips: ['*_test.py', '*/test_*.py']  # Skip assertions in tests

skips: []  # Additional skips
