# Build
FROM golang:1.22-bookworm AS builder

WORKDIR /src

COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /out/app ./cmd/main.go

# Runtime
FROM gcr.io/distroless/base-debian12:nonroot

WORKDIR /app
COPY --from=builder /out/app ./app

ENV PORT={{PORT}}
EXPOSE {{PORT}}

USER nonroot:nonroot
ENTRYPOINT ["./app"]
